FROM python:3.8

# copy assets over to image
COPY . /src

# set the working directory
WORKDIR /src

# install dependancies
RUN pip3 install --user --no-cache-dir -r requirements.txt

# set PATH
ENV PATH="/home/ubuntu/anaconda3/envs/enc-gen-env"

# exposing endpoint port
EXPOSE 5005

ENTRYPOINT ["streamlit", "run", "frontend.py", "--server.port", "5005", "--server.address", "0.0.0.0"]